# Generated by Django 5.0.1 on 2024-01-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sujeto',
            name='cuit',
            field=models.IntegerField(default=0),
        ),
    ]
