# Generated by Django 5.0.1 on 2024-01-09 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_view', '0003_alter_sujeto_cuit'),
        ('location_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sujeto',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location_view.localidad'),
        ),
        migrations.DeleteModel(
            name='Localidad',
        ),
    ]
