# Generated by Django 5.0.1 on 2024-01-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remito_view', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remito',
            name='id_remito',
            field=models.IntegerField(default=0),
        ),
    ]
