# Generated by Django 5.0.1 on 2024-01-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remito_view', '0002_remito_id_remito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remito',
            name='id_remito',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
