# Generated by Django 5.0.1 on 2024-01-11 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remito_view', '0003_alter_remito_id_remito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remito',
            old_name='id_remito',
            new_name='nro_remito',
        ),
    ]
