# Generated by Django 5.0.1 on 2024-01-10 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_view', '0002_alter_pais_name_alter_provincia_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
